import type { Dict } from "./types";

/**
 * English content — the source of truth. `my.ts` / `th.ts` override only what
 * they translate; everything else falls back to this file.
 *
 * Source: SoeMoeHtetStephenResumev2.pdf. Anything NOT in the resume is copied
 * from the reference portfolio and tagged `PLACEHOLDER` — grep for it.
 */
export const en: Dict = {
  meta: {
    title: "Soe Moe Htet — Software Engineer",
    description:
      "AI-integrated software engineer building production services and agentic AI systems with CopilotKit, A2A and AG-UI. TypeScript, Python, FastAPI, React, Docker.",
  },
  brand: { handle: "soe-moe-htet", name: "Soe Moe Htet" },
  nav: {
    about: "About",
    skills: "Skills",
    experience: "Experience",
    projects: "Projects",
    notes: "Notes",
    contact: "Contact",
    menu: "Menu",
    downloadCv: "Download CV",
    switchLanguage: "Switch language",
    toggleTheme: "Toggle light / dark theme",
    skip: "Skip to content",
  },
  hero: {
    available: "Open to new opportunities", // PLACEHOLDER (reference: "Available for remote roles")
    name: "Soe Moe Htet",
    role: "Software Engineer",
    focus: "Agentic AI & production services · TypeScript · Python · FastAPI",
    statement:
      "I build production services and agentic AI products end to end — from the data model and API to a deployed React and TypeScript interface.",
    viewWork: "View work",
    downloadCv: "Download CV",
    cvType: "PDF",
    tags: ["TypeScript", "Python", "FastAPI", "React", "PostgreSQL", "Docker", "CopilotKit", "A2A", "AG-UI"],
    terminal: {
      file: "stephen-smh — shipped.log",
      whoamiCmd: "whoami",
      whoami: "Soe Moe Htet (Stephen) · Bangkok, Thailand · UTC+7",
      statsCmd: "stats --career",
      stats: [
        { value: "10", label: "roles and internships" },
        { value: "6", label: "platform APIs behind one registry" },
        { value: "3", label: "agent protocols: CopilotKit, A2A, AG-UI" },
        { value: "2", label: "hackathon wins" },
      ],
      availabilityCmd: "availability",
      availability: "Hybrid and remote — Bangkok, UTC+7", // PLACEHOLDER (reference: "Remote-ready — regular overlap arranged for US / EU teams")
    },
  },
  about: {
    eyebrow: "How I work",
    title: "About",
    paragraphs: [
      "I am a software engineer with a Software Engineering degree from KMITL, building production services and agentic AI systems. As a Forward Deployed Engineer at Tech Links Asia I shipped a social media management platform solo — from the data model and FastAPI / SQLAlchemy API through to a production-ready React and TypeScript frontend.",
      "Before that, at Smart Shift Solutions, I built backend business logic in Kotlin and Spring Boot for Supali CRM and Supali DOA, implemented RBAC and server-side validation, and helped on Context Hub — an internal developer tool that answers questions by autonomously searching every project repository.",
      "On AI my posture is AI-native: Claude Code and Cursor for implementation, debugging and review, with the quality bar held on everything generated. I design agent products with CopilotKit, A2A and AG-UI — structured input and output, prompt-injection defences and deterministic validation for reliable, auditable behaviour.",
      "I care about how software reaches users: Docker and Docker Compose, CI/CD pipelines, and observability with Grafana and k6 load testing. I am familiar with production rollout strategies — canary releases, blue/green deployments and feature flags.",
    ],
    principles: [
      {
        title: "AI-native, human-reviewed",
        body: "Claude Code and Cursor do the typing; I keep the quality bar on every generated line — implementation, debugging and code review.",
      },
      {
        title: "Deterministic validation",
        body: "Agents get structured input and output, prompt-injection defences and deterministic checks, so behaviour stays reliable and auditable.",
      },
      {
        title: "One abstraction, many channels",
        body: "Six platform APIs sit behind a single service registry, so a new integration plugs in without touching core logic.",
      },
      {
        title: "Tested like a QA",
        body: "A QA internship meant Playwright end-to-end tests, Jira bug tracking and release-readiness reviews — habits I bring to every build.",
      },
    ],
    collabTitle: "Collaboration",
    collab: [
      { label: "Tools", value: "Jira, Asana, Trello, GitHub, GitLab, Figma, TestMo, Claude Code, Cursor" },
      {
        label: "Working style",
        value: "SCRUM and Agile collaboration — daily stand-ups, regression testing cycles and release-readiness reviews",
      },
      { label: "Availability", value: "Based in Bangkok (UTC+7); experienced with hybrid and remote work" }, // PLACEHOLDER
    ],
    educationTitle: "Education",
    education: [
      {
        school: "King Mongkut’s Institute of Technology Ladkrabang",
        degree: "Software Engineering — fresh graduate",
        period: "2022 – 2026",
      },
      {
        school: "Yangon Technological University",
        degree: "Information Technology — third year",
        period: "2018 – 2021",
      },
    ],
    languagesTitle: "Languages",
    languages: [
      { name: "Burmese", level: "Native" }, // PLACEHOLDER — not in resume
      { name: "English", level: "Professional working proficiency" }, // PLACEHOLDER — not in resume
    ],
    awardsTitle: "Awards",
    awards: ["ASEAN-INDIA Hackathon 2021 — winner", "Ooredoo Hackathon 2018 — Best Business Idea, Yangon, Myanmar"],
    activitiesTitle: "Beyond work",
    activities: [
      {
        title: "Teaching assistant, Introduction to Logic",
        body: "Wrote tutorials for each assignment and recorded offline video sessions on the lectures.",
      },
      {
        title: "ASEAN Data Science Explorers 2021",
        body: "Built a SAP Analytics storyboard on e-waste management trends, aligned with the UN SDGs.",
      },
      {
        title: "Build-on Thailand, Pattaya 2023",
        body: "Pitched facial-recognition features for digital banking (organised by depa, AWS, KrungThai and Central Tech).",
      },
      {
        title: "Arduino robotics competitions",
        body: "Built Arduino cars that sense objects, sound and vibration, with electric motors and micro-controllers.",
      },
      {
        title: "UNCTAD Entrepreneurship Training Workshop",
        body: "Certified programme on how start-up businesses work.",
      },
    ],
  },
  skills: {
    eyebrow: "Daily toolkit",
    title: "Technical skills",
    groups: [
      {
        title: "AI / Agentic Engineering",
        desc: "Agent products built on open protocols, with structured I/O and deterministic validation.",
        tags: [
          "A2A",
          "AG-UI",
          "CopilotKit AI SDK",
          "Agno",
          "LlamaIndex",
          "Multi-agent design",
          "RAG",
          "Prompt-injection defences",
          "Structured output",
          "Prompt templates",
          "n8n workflows",
          "Huawei Hi Agent (POC)",
        ],
      },
      {
        title: "Frontend & Mobile",
        desc: "React and TypeScript interfaces, from Figma design to production.",
        tags: [
          "React",
          "Next.js",
          "TypeScript",
          "JavaScript",
          "HTML / CSS",
          "Tailwind CSS",
          "Three.js",
          "Figma",
          "Reusable components & hooks",
          "Flutter",
          "Provider",
          "Bloc / Cubit",
        ],
      },
      {
        title: "Backend",
        desc: "Python and Kotlin services with clear, typed boundaries.",
        tags: [
          "Python",
          "FastAPI",
          "Flask",
          "SQLAlchemy",
          "Express.js",
          "Kotlin",
          "Spring Boot",
          "jOOQ",
          "Flyway",
          "REST API design",
          "RBAC",
          "Server-side validation",
        ],
      },
      {
        title: "Databases & Messaging",
        desc: "Relational, document and queue-based data flow.",
        tags: ["PostgreSQL", "MongoDB", "Firestore", "Firebase", "Redis", "RabbitMQ", "ZeroMQ"],
      },
      {
        title: "Real-time & IoT",
        desc: "Live data over sockets and brokers, from map dashboards to PLC-driven conveyors.",
        tags: ["WebSocket", "Socket.io", "ZeroMQ", "Python serial", "PLC data flow", "Google Maps API", "QR & proximity sensors"],
      },
      {
        title: "Infrastructure & DevOps",
        desc: "Containerised deployments, pipelines and safe rollouts.",
        tags: [
          "Docker",
          "Docker Compose",
          "GitHub Actions",
          "GitLab CI",
          "AWS",
          "Render",
          "Grafana",
          "k6 load testing",
          "Canary releases",
          "Blue / green",
          "Feature flags",
        ],
      },
      {
        title: "Testing & QA",
        desc: "The gate between fast delivery and risk.",
        tags: ["Playwright", "End-to-end tests", "Manual QA", "TestMo", "Jira", "Regression testing", "SCRUM", "Agile"],
      },
      {
        title: "AI-Assisted Delivery",
        desc: "AI-native workflow with a human quality bar.",
        tags: ["Claude Code", "Cursor", "Lovable", "Code review of generated output", "Prompt design for codegen"],
      },
    ],
  },
  experience: {
    eyebrow: "Roles & internships",
    title: "Experience",
    items: [
      {
        role: "Forward Deployed Engineer (associate)",
        org: "Tech Links Asia",
        period: "Jul 2026 – Present",
        summary: "A social media management platform, shipped solo from spec to deploy.",
        bullets: [
          "Owned the full delivery pipeline end-to-end — from data model and API design (FastAPI / SQLAlchemy) to a production-ready React / TypeScript frontend — shipping a working social media management platform solo, from spec to deploy.",
          "Integrated and stood up connections across six external platform APIs (Facebook, Instagram, LinkedIn, TikTok, X / Twitter, YouTube) behind a unified service-registry abstraction, so new channel integrations plug in without touching core logic.",
          "Embedded an AI copilot directly into user-facing workflows (composer, post editing) to translate a product need — faster content creation — into a working, deployed feature rather than a backlog item.",
          "Configured and deployed the full stack to production infrastructure (Docker, docker-compose, Render), closing the loop from code to a live, usable system rather than stopping at a local demo.",
        ],
        tags: ["Claude Code", "Lovable", "AWS", "GitHub Actions", "FastAPI", "SQLAlchemy", "React", "TypeScript"],
      },
      {
        role: "Software Engineer",
        org: "Smart Shift Solutions",
        period: "Dec 2025 – May 2026",
        place: "Hybrid",
        kind: "Internship",
        summary: "Backend business logic for internal CRM and DOA platforms, plus agentic tooling and AI proposals.",
        bullets: [
          "Built backend business logic modules (config, flow orchestration, position management) for Supali CRM and Supali DOA using Kotlin and Spring Boot, integrated with a Next.js frontend across the full request lifecycle.",
          "Implemented RBAC and server-side validation to enforce data boundaries and prevent unauthorized state changes across internal platforms.",
          "Helped on the Context Hub project, an internal developer tool that answers questions by autonomously searching across all project repositories — a retrieval-augmented, agentic lookup system that reduced cross-team information bottlenecks.",
          "Assisted in Docker builds for the Mitr Phol project, gaining hands-on exposure to containerised service packaging and deployment workflows.",
          "Worked AI-native throughout — using Claude Code and Cursor (company-sponsored) for implementation, debugging and code review, maintaining the quality bar on all generated output.",
          "Designed and proposed an agentic AI admin commerce platform on Agno using CopilotKit AI, incorporating structured input / output, prompt-injection defences and deterministic validation for reliable, auditable agent behaviour.",
          "Proposed an n8n-based internal workflow automation layer to eliminate repetitive document handling.",
        ],
        tags: ["Next.js", "Kotlin", "Spring Boot", "MVC", "jOOQ", "Flyway", "GitHub Actions", "Docker", "Claude Code"],
      },
      {
        role: "Quality Assurance Engineer",
        org: "Social.plus Co. Ltd.",
        period: "Jul 2025 – Sep 2025",
        place: "Hybrid",
        kind: "Internship",
        summary: "End-to-end test automation for a reusable social UI kit.",
        bullets: [
          "Collaborated with the QA team to test and ensure the quality of the Social.plus UI Kit, a reusable component library powering social features across client platforms.",
          "Wrote and maintained automated end-to-end test scripts using Playwright on the Social.plus UI Kit to validate UI component functionality and user flows.",
          "Identified, reported and tracked bugs using Jira, contributing to faster turnaround in agile sprints.",
          "Documented and managed test cases and results in TestMo for both manual and automated tests.",
          "Worked with developers and designers to verify UI / UX consistency across multiple environments.",
          "Leveraged Cursor AI to streamline test development and increase automation coverage.",
          "Joined daily stand-ups, regression testing cycles and release-readiness reviews as part of the QA team.",
        ],
        tags: ["Playwright", "Jira", "TestMo", "Node.js", "Social.plus UI Kit"],
      },
      {
        role: "Junior Python Programmer",
        org: "Zojump Co. Ltd",
        period: "Jul 2025",
        place: "Remote",
        kind: "Freelance",
        summary: "Working with Senior DevOps Engineer Vladimir (Cageyv) Samoylov — LlamaIndex, Docker, multi-agent.",
        bullets: [
          "Helped build a system that converts natural-language prompts into SQL queries using the LlamaIndex framework.",
          "Designed a multi-agent architecture where each agent handled specific tasks (e.g. query parsing, validation, optimisation).",
          "Containerised the entire pipeline with Docker to ensure isolated, reproducible environments for testing and deployment.",
          "Collaborated on DevOps workflows including Docker orchestration and continuous integration setups.",
          "Suggested prompt templates and agent strategies to improve query accuracy and reduce hallucination in generated SQL.",
        ],
        tags: ["Python", "LlamaIndex", "Docker", "Multi-agent"],
      },
      {
        role: "Full-stack Programmer",
        org: "Clara Robotic Co. Ltd",
        period: "Jun 2025 – Jul 2025",
        kind: "Part-time",
        summary: "A conveyor control system spanning PLC data, message brokers and a real-time web UI.",
        bullets: [
          "Developed a full-stack conveyor project using Python Flask and WebSocket for real-time data communication.",
          "Implemented Python serial communication and a ZeroMQ message broker to manage data flow from PLC controllers.",
          "Enhanced operation efficiency by integrating QR and proximity sensors, improving conveyor movement accuracy.",
        ],
        tags: ["Python", "Flask", "ZeroMQ", "React", "Docker", "Docusaurus"],
      },
      {
        role: "AI-augmented Developer",
        org: "Stream IT Consulting Co. Ltd",
        period: "Jun 2025",
        kind: "Internship",
        summary: "On-premise proof-of-concept testing of Huawei’s Hi Agent and CubeX systems.",
        bullets: [
          "Went to the Huawei office at G-Tower to test the Hi Agent and CubeX systems in POC testing — to understand how Huawei AI can integrate with prompts, build multi-agents and RAG applications (similar to LangChain).",
          "Ended the internship early due to schedule conflicts with university; Hi Agent and CubeX can only be tested on on-premise hardware at G-Tower.",
        ],
        tags: ["Huawei Hi Agent", "CubeX", "RAG", "Multi-agent"],
      },
      {
        role: "Full-stack Developer",
        org: "Demeter ICT",
        period: "Apr 2025 – Jun 2025",
        place: "Hybrid",
        kind: "Internship",
        summary: "A Braze test app in Flutter, then manual QA on the CXBOX product.",
        bullets: [
          "Developed an internal mobile testing app with CRM features — IAM, content cards with the Braze SDK — in Flutter, to test Braze features for a customer so that in-app messages, push notifications and content cards from Braze campaigns reach the customer.",
          "Collaborated with full-time developers and team members on the company website for POC testing and API testing.",
          "Transitioned to manual QA testing of CXBOX, leveraging analytical skills to identify and resolve software issues.",
          "Contributed to the development of CXBOX (cxbox.io), driving innovation in a hybrid work environment at Demeter ICT.",
        ],
        tags: ["HTML", "CSS", "JavaScript", "React", "Node.js", "Flutter", "Provider", "GitLab", "Firebase", "Figma"],
      },
      {
        role: "Full-stack Web Developer",
        org: "Sustainity",
        period: "Apr 2025 – May 2025",
        kind: "Internship",
        summary: "Emission-tracking dashboard and live vehicle geotracking.",
        bullets: [
          "Fixed UI inconsistencies in the dashboard that tracks emissions, and contributed to the live geotracking of transportation vehicles.",
          "Implemented the Google Locations API for place autocomplete, and contributed to event-based communication between the system and vehicles to keep live socket communication so routes are optimised.",
          "Built custom UI components and React hooks for reusable components and a scalable UI for other developers.",
        ],
        tags: ["React", "Firebase", "Express.js", "WebSocket", "GitLab", "Google Maps API"],
      },
      {
        role: "Flutter Developer",
        org: "Frontware International Co. Ltd",
        period: "Apr 2024 – Jun 2024",
        kind: "Internship",
        summary: "UI refactors and Cubit-driven state management on a customer Flutter codebase.",
        bullets: [
          "Refactored UI components in the company codebase to align with the provided Figma design.",
          "Fixed common UI components (Input, Datetime), reviewed the codebase and collaborated with a senior Flutter developer on an urgent customer requirement.",
          "Helped with state management using Cubit so UI rendering follows incoming stream events.",
        ],
        tags: ["Flutter", "Provider", "Bloc", "GitLab", "Firebase", "Figma"],
      },
      {
        role: "Full-stack Software Developer",
        org: "Chindwin Crewing Services Co. Ltd",
        period: "Feb 2020 – Apr 2022",
        summary: "Web systems for company operations and internal management.",
        bullets: [
          "Supported the development, improvement and maintenance of web-based systems used for company operations and internal management.",
          "Assisted in implementing website and system features related to data entry, record management, reporting and internal coordination.",
          "Helped improve web interfaces, user experience, system usability and accessibility of internal digital tools.",
          "Supported frontend and backend tasks under the guidance of relevant team members.",
          "Participated in testing web functions, identifying bugs, reporting issues and supporting fixes.",
        ],
        tags: ["React", "Python", "FastAPI"],
      },
    ],
  },
  projects: {
    eyebrow: "Engineering case studies",
    title: "Selected work",
    placeholderLabel: "Placeholder",
    items: [
      {
        kicker: "Tech Links Asia · Social media management",
        title: "A social media platform — six channels behind one registry",
        desc: "Shipped solo from spec to deploy: FastAPI / SQLAlchemy API, a production React / TypeScript frontend, and an AI copilot embedded in the composer and post editing.",
        stats: [
          { value: "6", label: "platform APIs behind one service registry" },
          { value: "1", label: "engineer, spec to deploy" },
          { value: "AI", label: "copilot in composer and post editing" },
          { value: "Render", label: "Docker Compose production deploy" },
        ],
        tags: ["FastAPI", "SQLAlchemy", "React", "TypeScript", "Docker"],
      },
      {
        kicker: "Zojump · Multi-agent SQL",
        title: "Natural language to SQL — a multi-agent pipeline",
        desc: "A LlamaIndex system that turns prompts into SQL, with separate agents for query parsing, validation and optimisation, containerised end to end with Docker.",
        stats: [
          { value: "NL→SQL", label: "natural-language prompts to queries" },
          { value: "Agents", label: "parse · validate · optimise" },
          { value: "Docker", label: "isolated, reproducible environments" },
        ],
        tags: ["Python", "LlamaIndex", "Docker", "Multi-agent"],
      },
      {
        kicker: "Smart Shift Solutions · Internal tool",
        badge: "Internal",
        title: "Context Hub — agentic lookup across every repository",
        desc: "An internal developer tool that answers questions by autonomously searching all project repositories — retrieval-augmented and agentic, cutting cross-team information bottlenecks.",
        stats: [
          { value: "RAG", label: "retrieval-augmented answers" },
          { value: "Agentic", label: "autonomous repository search" },
        ],
        tags: ["Agentic AI", "RAG", "Internal tooling"],
      },
      {
        kicker: "Smart Shift Solutions · Proposal",
        badge: "Proposal",
        title: "An agentic admin commerce platform on Agno",
        desc: "A designed and proposed agent platform on Agno and CopilotKit, built for reliable, auditable behaviour rather than free-form generation.",
        stats: [
          { value: "I/O", label: "structured input and output" },
          { value: "Guard", label: "prompt-injection defences" },
          { value: "Rules", label: "deterministic validation" },
        ],
        tags: ["Agno", "CopilotKit", "Agentic AI", "Security"],
      },
      {
        kicker: "Clara Robotic · Part-time",
        title: "A conveyor control system — PLC data to a live web UI",
        desc: "Python Flask and WebSocket for real-time data, serial communication and a ZeroMQ broker managing PLC controller flow, with QR and proximity sensors improving movement accuracy.",
        stats: [
          { value: "WS", label: "real-time WebSocket data" },
          { value: "ZeroMQ", label: "broker for PLC data flow" },
          { value: "QR", label: "and proximity sensors" },
        ],
        tags: ["Python", "Flask", "ZeroMQ", "React", "Docker"],
      },

      // ---- PLACEHOLDERS: copied from the reference portfolio. Replace or delete. ----
      {
        kicker: "Conexa · B2B networking & CRM platform",
        title: "AI Connector — an in-product agentic assistant",
        desc: "A streaming tool-use loop with 13 tools, one wire protocol implemented twice: TypeScript for web, Go for realtime.",
        stats: [
          { value: "13", label: "tools in the registry" },
          { value: "2", label: "implementations, 1 protocol" },
          { value: "3", label: "provider failover stages" },
          { value: "0", label: "duplicated ACLs for the agent" },
        ],
        tags: ["Agentic AI", "LLM", "TypeScript", "Go"],
        placeholder: true,
      },
      {
        kicker: "Conexa · Integration infrastructure",
        title: "A Go MCP server — opening the platform to external agents",
        desc: "Streamable HTTP, JWT verified at the edge, per-scope consent stored in PostgreSQL and requested through MCP elicitation.",
        stats: [
          { value: "JWT", label: "verified at the edge" },
          { value: "1×", label: "consent asked, revocable" },
          { value: "MCP", label: "elicitation per scope" },
        ],
        tags: ["MCP", "Go", "Security"],
        placeholder: true,
      },
      {
        kicker: "Conexa · Advertising automation for an e-commerce agency",
        title: "An ads automation platform — three surfaces on one Go backend",
        desc: "I built the system in TypeScript/Node, moved it to Go services myself with parity tests as the acceptance gate, then built the two Next.js surfaces on top: an operations console for the agency and a public landing site reading its CMS from that same backend.",
        stats: [
          { value: "~91k", label: "lines of Go across 406 files" },
          { value: "145", label: "test files alongside the Go build" },
          { value: "6", label: "Go services replacing one Node process" },
          { value: "52", label: "operations screens in the admin console" },
        ],
        tags: ["Go", "Microservices", "Next.js", "Agentic AI"],
        placeholder: true,
      },
      {
        kicker: "Personal project · Playable on the web",
        title: "Deep-sea spearfishing — a multiplayer 3D game in the browser",
        desc: "A Go server owning every rule at a 20Hz tick, a Babylon.js client, one protobuf schema generating both sides — and voice chat riding that same WebSocket instead of WebRTC.",
        stats: [
          { value: "20Hz", label: "server-authoritative simulation tick" },
          { value: "100", label: "players per room, tick under 50ms" },
          { value: "~270KB", label: "gzip for the 3D bundle, a 9KB lobby" },
          { value: "64kbps", label: "voice over WebSocket, no WebRTC" },
        ],
        tags: ["Go", "Realtime", "Babylon.js", "WebSocket"],
        placeholder: true,
      },
      {
        kicker: "Self-directed open-source project",
        title: "NewEra AI Demo — agentic RAG for IoT and fintech",
        desc: "A hand-written agent loop on the Claude Messages API, hybrid retrieval benchmarked across four configurations, and the same tools exposed over MCP.",
        stats: [
          { value: "4", label: "retriever configurations benchmarked" },
          { value: "49", label: "automated tests" },
          { value: "BM25+", label: "dense vectors fused with RRF" },
        ],
        tags: ["RAG", "MCP", "Python", "Claude API"],
        placeholder: true,
      },
    ],
  },
  notes: {
    eyebrow: "Writing to think clearly",
    title: "Engineering notes",
    placeholderLabel: "Placeholder",
    // ---- PLACEHOLDERS: copied from the reference portfolio. Replace or delete. ----
    items: [
      {
        iso: "2026-06-02",
        date: "02 Jun 2026",
        read: "2 min read",
        title: "Porting a TypeScript monolith to Go without behavioural drift",
        desc: "I wrote the Node build, then moved it to Go myself. That sounds easier — until you notice that “I remember how it behaves” is not an acceptance criterion.",
        tags: ["Go", "Migration", "Testing"],
        placeholder: true,
      },
      {
        iso: "2026-03-18",
        date: "18 Mar 2026",
        read: "2 min read",
        title: "Do not write a separate ACL for your agent",
        desc: "Once an AI assistant can write data, the scary part is not a wrong answer from the model. It is a second permission layer quietly drifting away from the real one.",
        tags: ["Agentic AI", "Security", "Architecture"],
        placeholder: true,
      },
    ],
  },
  contact: {
    eyebrow: "Reply within 24 hours", // PLACEHOLDER (reference copy)
    title: "Get in touch",
    form: {
      name: "Name",
      namePh: "Your name",
      email: "Email",
      emailPh: "you@company.com",
      subject: "Subject",
      subjectPh: "Role, project, collaboration…",
      message: "Message",
      messagePh: "A short description of the need, scope and timeline.",
      send: "Send message",
      opening: "Opening your email app…",
      invalid: "Please fill in every field with a valid email.",
    },
    direct: {
      title: "Or reach me directly",
      emailLabel: "Email",
      email: "soemoehtetstephen@gmail.com",
      githubLabel: "GitHub",
      github: "Stephen-smh",
      githubUrl: "https://github.com/Stephen-smh",
      linkedinLabel: "LinkedIn",
      linkedin: "soe-moe-htet-01b411187",
      linkedinUrl: "https://www.linkedin.com/in/soe-moe-htet-01b411187/",
      phoneLabel: "Phone",
      phoneMasked: "093 ••• ••••",
      reveal: "Click to reveal",
      revealAria: "Show the phone number",
      hiddenNote: "Hidden from the page so scrapers cannot harvest it.",
    },
    card: {
      locationCmd: "location",
      location: "Lat Krabang, Bangkok, Thailand · UTC+7",
      availabilityCmd: "availability",
      availability: "Hybrid and remote — open to new opportunities", // PLACEHOLDER
    },
  },
  footer: {
    built: "Built with Next.js, TypeScript and Tailwind CSS.",
    rights: "All rights reserved.",
    github: "GitHub",
    linkedin: "LinkedIn",
    email: "Email",
  },
};
