import type { Dict } from "./types";

/**
 * English content - the source of truth. `my.ts` / `th.ts` override only what
 * they translate; everything else falls back to this file.
 *
 * Source: SoeMoeHtetStephenResumev2.pdf. Anything NOT in the resume is copied
 * from the reference portfolio and tagged `PLACEHOLDER` - grep for it.
 */
export const en: Dict = {
  meta: {
    title: "Soe Moe Htet - Software Engineer",
    description:
      "AI-integrated software engineer building production services and agentic AI systems with CopilotKit, A2A and AG-UI. TypeScript, Python, FastAPI, React, Docker.",
  },
  brand: { handle: "soe-moe-htet", name: "Soe Moe Htet" },
  nav: {
    about: "About",
    skills: "Skills",
    experience: "Experience",
    projects: "Projects",
    notes: "Notes",
    contact: "Contact",
    menu: "Menu",
    downloadCv: "Download CV",
    switchLanguage: "Switch language",
    toggleTheme: "Toggle light / dark theme",
    skip: "Skip to content",
  },
  hero: {
    available: "Open to new opportunities", // PLACEHOLDER (reference: "Available for remote roles")
    name: "Soe Moe Htet",
    role: "Software Engineer",
    focus: "Agentic AI & production services · TypeScript · Python · FastAPI",
    statement:
      "I build production services and agentic AI products end to end - from the data model and API to a deployed React and TypeScript interface.",
    viewWork: "View work",
    downloadCv: "Download CV",
    cvType: "PDF",
    tags: ["TypeScript", "Python", "FastAPI", "React", "PostgreSQL", "Docker", "CopilotKit", "A2A", "AG-UI"],
    terminal: {
      file: "stephen-smh - shipped.log",
      whoamiCmd: "whoami",
      whoami: "Soe Moe Htet (Stephen) · Bangkok, Thailand · UTC+7",
      statsCmd: "stats --career",
      stats: [
        { value: "10", label: "roles and internships" },
        { value: "6", label: "platform APIs behind one registry" },
        { value: "3", label: "agent protocols: CopilotKit, A2A, AG-UI" },
        { value: "2", label: "hackathon wins" },
      ],
      availabilityCmd: "availability",
      availability: "Hybrid and remote - Bangkok, UTC+7", // PLACEHOLDER (reference: "Remote-ready - regular overlap arranged for US / EU teams")
    },
  },
  about: {
    eyebrow: "How I work",
    title: "About",
    paragraphs: [
      "Software engineer building production services and agentic AI systems.",
      "I shipped a social media platform solo at Tech Links Asia, and wrote Kotlin / Spring Boot backends at Smart Shift Solutions.",
    ],
    principles: [
      {
        title: "AI-native, human-reviewed",
        body: "Claude Code and Cursor write; I review every line.",
      },
      {
        title: "Deterministic validation",
        body: "Structured I/O and injection defences keep agents auditable.",
      },
      {
        title: "One abstraction, many channels",
        body: "Six platform APIs behind one service registry.",
      },
      {
        title: "Tested like a QA",
        body: "Playwright E2E, Jira tracking, release-readiness reviews.",
      },
      {
        title: "Backend that holds up",
        body: "Kotlin and Spring Boot, with RBAC and server-side validation.",
      },
      {
        title: "Ships to production",
        body: "Docker, CI/CD, Grafana and k6; canary and blue/green rollouts.",
      },
    ],
    collabTitle: "Collaboration",
    collab: [
      { label: "Tools", value: "Jira, Asana, Trello, GitHub, GitLab, Figma, TestMo, Claude Code, Cursor" },
      { label: "Working style", value: "SCRUM · Agile · stand-ups · regression cycles" },
      { label: "Availability", value: "Bangkok (UTC+7) · hybrid or remote" }, // PLACEHOLDER
    ],
    educationTitle: "Education",
    education: [
      {
        school: "KMITL",
        degree: "B.Eng. Software Engineering",
        period: "2022 – 2026",
      },
      {
        school: "Yangon Technological University",
        degree: "Information Technology",
        period: "2018 – 2021",
      },
    ],
    languagesTitle: "Languages",
    languages: [
      { name: "Burmese", level: "Native", bars: 5 }, // PLACEHOLDER - not in resume
      { name: "English", level: "Professional", bars: 4 }, // PLACEHOLDER - not in resume
    ],
    awardsTitle: "Awards",
    awards: ["ASEAN-INDIA Hackathon 2021 · winner", "Ooredoo Hackathon 2018 · Best Business Idea"],
    activitiesTitle: "Beyond work",
    activities: [
      {
        title: "Teaching assistant · Logic",
        body: "Wrote tutorials for each assignment and recorded offline video sessions on the lectures.",
      },
      {
        title: "ASEAN Data Science Explorers 2021",
        body: "Built a SAP Analytics storyboard on e-waste management trends, aligned with the UN SDGs.",
      },
      {
        title: "Build-on Thailand 2023",
        body: "Pitched facial-recognition features for digital banking (organised by depa, AWS, KrungThai and Central Tech).",
      },
      {
        title: "Arduino robotics",
        body: "Built Arduino cars that sense objects, sound and vibration, with electric motors and micro-controllers.",
      },
      {
        title: "UNCTAD Entrepreneurship Workshop",
        body: "Certified programme on how start-up businesses work.",
      },
    ],
  },
  build: {
    eyebrow: "Idea to device",
    title: "Code in, product out",
    steps: [
      { title: "Commit", desc: "Code is typed with AI as a pair, then pushed." },
      { title: "Build", desc: "Containers are built on every push." },
      { title: "Test", desc: "Unit and end-to-end tests gate the release." },
      { title: "Deploy", desc: "It lands on a real phone, live." },
    ],
  },
  concepts: {
    eyebrow: "Engineering in pictures",
    title: "How I think",
    items: [
      { tag: "Database", title: "Normalization", desc: "Split one wide table into related ones, so each fact lives in exactly one place." },
      { tag: "DevOps", title: "CI/CD loop", desc: "Every commit is built, tested and deployed, then watched in production." },
      { tag: "Full stack", title: "Request path", desc: "React in the browser, an API in the middle, PostgreSQL and a cache behind it." },
      { tag: "Security", title: "Defence in depth", desc: "Auth, validation and encryption, so one failed layer is not a breach." },
      { tag: "System design", title: "Scale out", desc: "A load balancer spreads traffic over stateless servers; reads hit a cache or replica." },
      { tag: "Use case", title: "Social post scheduler", desc: "Who does what in the system: an actor, a boundary and the goals inside it." },
    ],
  },
  skills: {
    eyebrow: "Daily toolkit",
    title: "Technical skills",
    groups: [
      {
        title: "AI / Agentic Engineering",
        desc: "Agent products built on open protocols, with structured I/O and deterministic validation.",
        tags: [
          "A2A",
          "AG-UI",
          "CopilotKit AI SDK",
          "Agno",
          "LlamaIndex",
          "Multi-agent design",
          "RAG",
          "Prompt-injection defences",
          "Structured output",
          "Prompt templates",
          "n8n workflows",
          "Huawei Hi Agent (POC)",
        ],
      },
      {
        title: "Frontend & Mobile",
        desc: "React and TypeScript interfaces, from Figma design to production.",
        tags: [
          "React",
          "Next.js",
          "TypeScript",
          "JavaScript",
          "HTML / CSS",
          "Tailwind CSS",
          "Three.js",
          "Figma",
          "Reusable components & hooks",
          "Flutter",
          "Provider",
          "Bloc / Cubit",
        ],
      },
      {
        title: "Backend",
        desc: "Python and Kotlin services with clear, typed boundaries.",
        tags: [
          "Python",
          "FastAPI",
          "Flask",
          "SQLAlchemy",
          "Express.js",
          "Kotlin",
          "Spring Boot",
          "jOOQ",
          "Flyway",
          "REST API design",
          "RBAC",
          "Server-side validation",
        ],
      },
      {
        title: "Databases & Messaging",
        desc: "Relational, document and queue-based data flow.",
        tags: ["PostgreSQL", "MongoDB", "Firestore", "Firebase", "Redis", "RabbitMQ", "ZeroMQ"],
      },
      {
        title: "Real-time & IoT",
        desc: "Live data over sockets and brokers, from map dashboards to PLC-driven conveyors.",
        tags: ["WebSocket", "Socket.io", "ZeroMQ", "Python serial", "PLC data flow", "Google Maps API", "QR & proximity sensors"],
      },
      {
        title: "Infrastructure & DevOps",
        desc: "Containerised deployments, pipelines and safe rollouts.",
        tags: [
          "Docker",
          "Docker Compose",
          "GitHub Actions",
          "GitLab CI",
          "AWS",
          "Render",
          "Grafana",
          "k6 load testing",
          "Canary releases",
          "Blue / green",
          "Feature flags",
        ],
      },
      {
        title: "Testing & QA",
        desc: "The gate between fast delivery and risk.",
        tags: ["Playwright", "End-to-end tests", "Manual QA", "TestMo", "Jira", "Regression testing", "SCRUM", "Agile"],
      },
      {
        title: "AI-Assisted Delivery",
        desc: "AI-native workflow with a human quality bar.",
        tags: ["Claude Code", "Cursor", "Lovable", "Code review of generated output", "Prompt design for codegen"],
      },
    ],
  },
  experience: {
    eyebrow: "Roles & internships",
    title: "Experience",
    items: [
      {
        role: "Forward Deployed Engineer (associate)",
        org: "Tech Links Asia",
        period: "Jul 2026 – Present",
        summary: "A social media management platform, shipped solo from spec to deploy.",
        bullets: [
          "Owned the full delivery pipeline end-to-end - from data model and API design (FastAPI / SQLAlchemy) to a production-ready React / TypeScript frontend - shipping a working social media management platform solo, from spec to deploy.",
          "Integrated and stood up connections across six external platform APIs (Facebook, Instagram, LinkedIn, TikTok, X / Twitter, YouTube) behind a unified service-registry abstraction, so new channel integrations plug in without touching core logic.",
          "Embedded an AI copilot directly into user-facing workflows (composer, post editing) to translate a product need - faster content creation - into a working, deployed feature rather than a backlog item.",
          "Configured and deployed the full stack to production infrastructure (Docker, docker-compose, Render), closing the loop from code to a live, usable system rather than stopping at a local demo.",
        ],
        tags: ["Claude Code", "Lovable", "AWS", "GitHub Actions", "FastAPI", "SQLAlchemy", "React", "TypeScript"],
      },
      {
        role: "Software Engineer",
        org: "Smart Shift Solutions",
        period: "Dec 2025 – May 2026",
        place: "Hybrid",
        kind: "Internship",
        summary: "Backend business logic for internal CRM and DOA platforms, plus agentic tooling and AI proposals.",
        bullets: [
          "Built backend business logic modules (config, flow orchestration, position management) for Supali CRM and Supali DOA using Kotlin and Spring Boot, integrated with a Next.js frontend across the full request lifecycle.",
          "Implemented RBAC and server-side validation to enforce data boundaries and prevent unauthorized state changes across internal platforms.",
          "Helped on the Context Hub project, an internal developer tool that answers questions by autonomously searching across all project repositories - a retrieval-augmented, agentic lookup system that reduced cross-team information bottlenecks.",
          "Assisted in Docker builds for the Mitr Phol project, gaining hands-on exposure to containerised service packaging and deployment workflows.",
          "Worked AI-native throughout - using Claude Code and Cursor (company-sponsored) for implementation, debugging and code review, maintaining the quality bar on all generated output.",
          "Designed and proposed an agentic AI admin commerce platform on Agno using CopilotKit AI, incorporating structured input / output, prompt-injection defences and deterministic validation for reliable, auditable agent behaviour.",
          "Proposed an n8n-based internal workflow automation layer to eliminate repetitive document handling.",
        ],
        tags: ["Next.js", "Kotlin", "Spring Boot", "MVC", "jOOQ", "Flyway", "GitHub Actions", "Docker", "Claude Code"],
      },
      {
        role: "Quality Assurance Engineer",
        org: "Social.plus Co. Ltd.",
        period: "Jul 2025 – Sep 2025",
        place: "Hybrid",
        kind: "Internship",
        summary: "End-to-end test automation for a reusable social UI kit.",
        bullets: [
          "Collaborated with the QA team to test and ensure the quality of the Social.plus UI Kit, a reusable component library powering social features across client platforms.",
          "Wrote and maintained automated end-to-end test scripts using Playwright on the Social.plus UI Kit to validate UI component functionality and user flows.",
          "Identified, reported and tracked bugs using Jira, contributing to faster turnaround in agile sprints.",
          "Documented and managed test cases and results in TestMo for both manual and automated tests.",
          "Worked with developers and designers to verify UI / UX consistency across multiple environments.",
          "Leveraged Cursor AI to streamline test development and increase automation coverage.",
          "Joined daily stand-ups, regression testing cycles and release-readiness reviews as part of the QA team.",
        ],
        tags: ["Playwright", "Jira", "TestMo", "Node.js", "Social.plus UI Kit"],
      },
      {
        role: "Junior Python Programmer",
        org: "Zojump Co. Ltd",
        period: "Jul 2025",
        place: "Remote",
        kind: "Freelance",
        summary: "Working with Senior DevOps Engineer Vladimir (Cageyv) Samoylov - LlamaIndex, Docker, multi-agent.",
        bullets: [
          "Helped build a system that converts natural-language prompts into SQL queries using the LlamaIndex framework.",
          "Designed a multi-agent architecture where each agent handled specific tasks (e.g. query parsing, validation, optimisation).",
          "Containerised the entire pipeline with Docker to ensure isolated, reproducible environments for testing and deployment.",
          "Collaborated on DevOps workflows including Docker orchestration and continuous integration setups.",
          "Suggested prompt templates and agent strategies to improve query accuracy and reduce hallucination in generated SQL.",
        ],
        tags: ["Python", "LlamaIndex", "Docker", "Multi-agent"],
      },
      {
        role: "Full-stack Programmer",
        org: "Clara Robotic Co. Ltd",
        period: "Jun 2025 – Jul 2025",
        kind: "Part-time",
        summary: "A conveyor control system spanning PLC data, message brokers and a real-time web UI.",
        bullets: [
          "Developed a full-stack conveyor project using Python Flask and WebSocket for real-time data communication.",
          "Implemented Python serial communication and a ZeroMQ message broker to manage data flow from PLC controllers.",
          "Enhanced operation efficiency by integrating QR and proximity sensors, improving conveyor movement accuracy.",
        ],
        tags: ["Python", "Flask", "ZeroMQ", "React", "Docker", "Docusaurus"],
      },
      {
        role: "AI-augmented Developer",
        org: "Stream IT Consulting Co. Ltd",
        period: "Jun 2025",
        kind: "Internship",
        summary: "On-premise proof-of-concept testing of Huawei’s Hi Agent and CubeX systems.",
        bullets: [
          "Went to the Huawei office at G-Tower to test the Hi Agent and CubeX systems in POC testing - to understand how Huawei AI can integrate with prompts, build multi-agents and RAG applications (similar to LangChain).",
          "Ended the internship early due to schedule conflicts with university; Hi Agent and CubeX can only be tested on on-premise hardware at G-Tower.",
        ],
        tags: ["Huawei Hi Agent", "CubeX", "RAG", "Multi-agent"],
      },
      {
        role: "Full-stack Developer",
        org: "Demeter ICT",
        period: "Apr 2025 – Jun 2025",
        place: "Hybrid",
        kind: "Internship",
        summary: "A Braze test app in Flutter, then manual QA on the CXBOX product.",
        bullets: [
          "Developed an internal mobile testing app with CRM features - IAM, content cards with the Braze SDK - in Flutter, to test Braze features for a customer so that in-app messages, push notifications and content cards from Braze campaigns reach the customer.",
          "Collaborated with full-time developers and team members on the company website for POC testing and API testing.",
          "Transitioned to manual QA testing of CXBOX, leveraging analytical skills to identify and resolve software issues.",
          "Contributed to the development of CXBOX (cxbox.io), driving innovation in a hybrid work environment at Demeter ICT.",
        ],
        tags: ["HTML", "CSS", "JavaScript", "React", "Node.js", "Flutter", "Provider", "GitLab", "Firebase", "Figma"],
      },
      {
        role: "Full-stack Web Developer",
        org: "Sustainity",
        period: "Apr 2025 – May 2025",
        kind: "Internship",
        summary: "Emission-tracking dashboard and live vehicle geotracking.",
        bullets: [
          "Fixed UI inconsistencies in the dashboard that tracks emissions, and contributed to the live geotracking of transportation vehicles.",
          "Implemented the Google Locations API for place autocomplete, and contributed to event-based communication between the system and vehicles to keep live socket communication so routes are optimised.",
          "Built custom UI components and React hooks for reusable components and a scalable UI for other developers.",
        ],
        tags: ["React", "Firebase", "Express.js", "WebSocket", "GitLab", "Google Maps API"],
      },
      {
        role: "Flutter Developer",
        org: "Frontware International Co. Ltd",
        period: "Apr 2024 – Jun 2024",
        kind: "Internship",
        summary: "UI refactors and Cubit-driven state management on a customer Flutter codebase.",
        bullets: [
          "Refactored UI components in the company codebase to align with the provided Figma design.",
          "Fixed common UI components (Input, Datetime), reviewed the codebase and collaborated with a senior Flutter developer on an urgent customer requirement.",
          "Helped with state management using Cubit so UI rendering follows incoming stream events.",
        ],
        tags: ["Flutter", "Provider", "Bloc", "GitLab", "Firebase", "Figma"],
      },
      {
        role: "Full-stack Software Developer",
        org: "Chindwin Crewing Services Co. Ltd",
        period: "Feb 2020 – Apr 2022",
        summary: "Web systems for company operations and internal management.",
        bullets: [
          "Supported the development, improvement and maintenance of web-based systems used for company operations and internal management.",
          "Assisted in implementing website and system features related to data entry, record management, reporting and internal coordination.",
          "Helped improve web interfaces, user experience, system usability and accessibility of internal digital tools.",
          "Supported frontend and backend tasks under the guidance of relevant team members.",
          "Participated in testing web functions, identifying bugs, reporting issues and supporting fixes.",
        ],
        tags: ["React", "Python", "FastAPI"],
      },
    ],
  },
  projects: {
    eyebrow: "Engineering case studies",
    title: "Selected work",
    placeholderLabel: "Placeholder",
    items: [
      {
        kicker: "Personal project · Open source · PostgreSQL",
        title: "Migrate Studio - run migrations, then see what they did",
        desc: "A Go binary with a React UI built in. It applies and rolls back SQL migrations safely, lints them for risky statements, replays every step on a scratch database to draw a schema timeline, proves each down really undoes its up, and catches changes made to the database by hand.",
        stats: [
          { value: "Drift", label: "live schema diffed against what the migrations should produce" },
          { value: "10", label: "lint rules, each pointing at a line and a fix" },
          { value: "Undo", label: "every down replayed and checked on a scratch database" },
          { value: "Go", label: "one binary with the React UI embedded" },
        ],
        tags: ["Go", "PostgreSQL", "React", "TypeScript", "GitHub Actions"],
        links: [
          { label: "Live demo", href: "https://stephen-smh.github.io/migrate-studio/" },
          { label: "Source on GitHub", href: "https://github.com/Stephen-SMH/migrate-studio" },
        ],
      },
      {
        kicker: "Tech Links Asia · Social media management",
        title: "A social media platform - six channels behind one registry",
        desc: "Shipped solo from spec to deploy: FastAPI / SQLAlchemy API, a production React / TypeScript frontend, and an AI copilot embedded in the composer and post editing.",
        stats: [
          { value: "6", label: "platform APIs behind one service registry" },
          { value: "1", label: "engineer, spec to deploy" },
          { value: "AI", label: "copilot in composer and post editing" },
          { value: "Render", label: "Docker Compose production deploy" },
        ],
        tags: ["FastAPI", "SQLAlchemy", "React", "TypeScript", "Docker"],
      },
      {
        kicker: "Zojump · Multi-agent SQL",
        title: "Natural language to SQL - a multi-agent pipeline",
        desc: "A LlamaIndex system that turns prompts into SQL, with separate agents for query parsing, validation and optimisation, containerised end to end with Docker.",
        stats: [
          { value: "NL→SQL", label: "natural-language prompts to queries" },
          { value: "Agents", label: "parse · validate · optimise" },
          { value: "Docker", label: "isolated, reproducible environments" },
        ],
        tags: ["Python", "LlamaIndex", "Docker", "Multi-agent"],
      },
      {
        kicker: "Smart Shift Solutions · Internal tool",
        badge: "Internal",
        title: "Context Hub - agentic lookup across every repository",
        desc: "An internal developer tool that answers questions by autonomously searching all project repositories - retrieval-augmented and agentic, cutting cross-team information bottlenecks.",
        stats: [
          { value: "RAG", label: "retrieval-augmented answers" },
          { value: "Agentic", label: "autonomous repository search" },
        ],
        tags: ["Agentic AI", "RAG", "Internal tooling"],
      },
      {
        kicker: "Smart Shift Solutions · Proposal",
        badge: "Proposal",
        title: "An agentic admin commerce platform on Agno",
        desc: "A designed and proposed agent platform on Agno and CopilotKit, built for reliable, auditable behaviour rather than free-form generation.",
        stats: [
          { value: "I/O", label: "structured input and output" },
          { value: "Guard", label: "prompt-injection defences" },
          { value: "Rules", label: "deterministic validation" },
        ],
        tags: ["Agno", "CopilotKit", "Agentic AI", "Security"],
      },
      {
        kicker: "Clara Robotic · Part-time",
        title: "A conveyor control system - PLC data to a live web UI",
        desc: "Python Flask and WebSocket for real-time data, serial communication and a ZeroMQ broker managing PLC controller flow, with QR and proximity sensors improving movement accuracy.",
        stats: [
          { value: "WS", label: "real-time WebSocket data" },
          { value: "ZeroMQ", label: "broker for PLC data flow" },
          { value: "QR", label: "and proximity sensors" },
        ],
        tags: ["Python", "Flask", "ZeroMQ", "React", "Docker"],
      },
      {
        kicker: "Personal project · Local LLM infrastructure",
        title: "LocalGate - an OpenAI-compatible gateway for local models",
        desc: "A self-hosted control plane between applications and local inference servers such as Ollama: one stable API, a model registry, retries, circuit breakers and fallback models, API-key RBAC and Redis-backed rate limiting.",
        stats: [
          { value: "OpenAI", label: "compatible API in front of local servers" },
          { value: "RBAC", label: "API keys, roles and per-key rate limits" },
          { value: "Resilient", label: "retries, circuit breakers, fallback models" },
        ],
        tags: ["LLM", "Gateway", "Redis", "Ollama"],
      },
      {
        kicker: "Personal project · Multi-agent simulation",
        title: "Food Delivery City - every character is an AI agent",
        desc: "A real-time delivery platform on a 3D map where customers, managers, cooks, counter staff and riders are agents driven by a local LLM. Go services talk over RabbitMQ with Postgres, all in Docker.",
        stats: [
          { value: "Agents", label: "every role on the map is an LLM agent" },
          { value: "Events", label: "RabbitMQ with an outbox pattern" },
          { value: "3D", label: "React + Three.js live client" },
        ],
        tags: ["Go", "RabbitMQ", "Three.js", "Agentic AI"],
      },
      {
        kicker: "Personal project · Cloud & DevOps",
        title: "YoteShin Platform - production-style infrastructure on free tooling",
        desc: "Infrastructure as code, Kubernetes, GitOps delivery, observability with SLOs and reliability practices for a short-drama streaming app, run locally on k3d and in the cloud with Terraform-managed resources.",
        stats: [
          { value: "IaC", label: "Terraform-managed cloud resources" },
          { value: "GitOps", label: "Kubernetes delivery" },
          { value: "SLOs", label: "observability and reliability" },
        ],
        tags: ["Kubernetes", "Terraform", "GitOps", "Observability"],
      },
      {
        kicker: "Personal project · Mobile",
        title: "YoteShin - a Flutter studio app for publishing films to YouTube",
        desc: "Uploads are handed to the OS transfer service so they continue in the background and resume from what YouTube already has after a dropped connection; a film shows as published only once YouTube returns its video ID.",
        stats: [
          { value: "BG", label: "background uploads on iOS and Android" },
          { value: "Resume", label: "continue from YouTube's received bytes" },
        ],
        tags: ["Flutter", "YouTube Data API", "Mobile"],
      },
      {
        kicker: "Personal project · Burmese speech AI",
        badge: "In progress",
        title: "Zaga - a Burmese voice engine",
        desc: "Text-to-speech, voice cloning and audiobooks for Burmese, starting with a finished text frontend (Zawgyi to Unicode, numbers as words, sentence splitting) ahead of model baselines and fine-tuning.",
        stats: [
          { value: "Text", label: "frontend complete" },
          { value: "TTS", label: "baselines and fine-tuning next" },
        ],
        tags: ["Python", "TTS", "NLP", "Burmese"],
      },
      {
        kicker: "Personal project · AI chat",
        title: "GenAI Language - a streaming Claude chat interface",
        desc: "A Next.js 16 App Router chat UI that streams responses from Claude through the Vercel AI SDK.",
        stats: [
          { value: "Stream", label: "token streaming from Claude" },
          { value: "Next 16", label: "App Router and server components" },
        ],
        tags: ["Next.js", "TypeScript", "Vercel AI SDK", "Claude API"],
      },
    ],
  },
  notes: {
    eyebrow: "Writing to think clearly",
    title: "Engineering notes",
    placeholderLabel: "Placeholder",
    items: [],
  },
  contact: {
    eyebrow: "Reply within 24 hours", // PLACEHOLDER (reference copy)
    title: "Get in touch",
    chat: {
      name: "Stephen",
      online: "online · replies within 24 hours",
      lead: "Pick a topic and we start talking.",
      hello: "Hi, I'm Stephen. Thanks for stopping by.",
      ask: "What brings you here?",
      options: [
        { label: "I'm hiring", subject: "Hiring: hello from your portfolio", reply: "Great, let's talk. Send me the role and team, and I'll reply within a day. Here is how to reach me:" },
        { label: "I have a project", subject: "Project: hello from your portfolio", reply: "Nice. A few lines on the idea, the timeline and what success looks like is plenty to start. Reach me here:" },
        { label: "Just saying hi", subject: "Hi from your portfolio", reply: "Hi back! Always happy to meet another builder. Say hello here:" },
      ],
      restart: "Start over",
      copy: "Copy email",
      copied: "Copied",
      skip: "Prefer plain email?",
    },
    form: {
      name: "Name",
      namePh: "Your name",
      email: "Email",
      emailPh: "you@company.com",
      subject: "Subject",
      subjectPh: "Role, project, collaboration…",
      message: "Message",
      messagePh: "A short description of the need, scope and timeline.",
      send: "Send message",
      opening: "Opening your email app…",
      invalid: "Please fill in every field with a valid email.",
    },
    direct: {
      title: "Or reach me directly",
      emailLabel: "Email",
      email: "soemoehtetstephen@gmail.com",
      githubLabel: "GitHub",
      github: "Stephen-smh",
      githubUrl: "https://github.com/Stephen-smh",
      linkedinLabel: "LinkedIn",
      linkedin: "soe-moe-htet-01b411187",
      linkedinUrl: "https://www.linkedin.com/in/soe-moe-htet-01b411187/",
      phoneLabel: "Phone",
      phoneMasked: "093 ••• ••••",
      reveal: "Click to reveal",
      revealAria: "Show the phone number",
      hiddenNote: "Hidden from the page so scrapers cannot harvest it.",
    },
    card: {
      locationCmd: "location",
      location: "Lat Krabang, Bangkok, Thailand · UTC+7",
      availabilityCmd: "availability",
      availability: "Hybrid and remote - open to new opportunities", // PLACEHOLDER
    },
  },
  footer: {
    built: "Built with Astro, TypeScript and Tailwind CSS.",
    rights: "All rights reserved.",
    github: "GitHub",
    linkedin: "LinkedIn",
    email: "Email",
    games: "Games",
  },
};
